// Generated by CoffeeScript 1.6.3
var routes;

routes = function(app) {
  app.get("/login", function(req, res) {
    return res.render("login", {
      login: "Having Fun with node"
    });
  });
  app.get("/", function(req, res) {
    return res.render("index", {
      title: "Simple Chat | We are having fun with node"
    });
  });
  return app.post("/sessions", function(req, res) {
    return res.redirect("/");
  });
};

module.exports = routes;
